---
# Where builds happen
- hosts: jenkins 
  become: yes
  gather_facts: yes

  # Variables
  vars_files:
    - jenkins/settings.yml
    - jenkins/common_secrets.yml
  no_log: true

  # Handers
  handlers:
    - name: Restart Jenkins
      service: name=jenkins state=restarted
  
  # Tasks
  tasks:
    # Setup Jenkins build jobs
    - include_tasks: jenkins/{{ item.jobDir }}/job.yml MyJobDir={{ item.jobDir }}
      with_items: "{{ build_jobs }}"
      no_log: false
