---
# The test_domain playbook is designed for testing connectivity 
# from the jenkins sever to ansible and ansible tower.
#
#
- hosts: tower
  become: yes
  become_user: root
  become_method: sudo
  #
  roles:
     - common  # common apps install and check
  tasks:
     - name: test copy a file
       copy:
          src: /etc/hosts
          dest: /opt/test/hosts2
          mode: 0644

