---
jenkins_url: tower.wfoai.com

# Stored in vault.yml
#####################################
# jenkins_username: 'XXXXXX'
# jenkins_admin_pass: 'XXXXXXXXXXXXXX'
# jenkens_token: 'XXXXXXXXXXXXXXXXXXX'
jenkens_host_url: http://tower.wfoai.com:8080


jenkins_plugins:
   - job-dsl
   - workflow-aggregator
   - workflow-cps
